version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=mysql
      - DB_HOST=gondola.proxy.rlwy.net
      - DB_PORT=14668
      - DB_DATABASE=railway
      - DB_USERNAME=root
      - DB_PASSWORD=BYwycoigujQGKRloFfbWIotCZfaIKWrZ
    volumes:
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
